### ISSUE TITLE
typo in lane's name

### ISSUE THREAD

**Issue by ligi** [avive/wasm_on_the_blockchain#2]
in the agenda lane is announced as "lane rettin" - but his name is "lane rettig" - unfortunately I cannot fix it via PR as the error is in an image and I do not see the source for it

**Comment by avive** [comment]
Good catch and thank you for this - I will fix ASAP - we have the agenda in a google shared cal...
I hope you plan attending!

**Comment by avive** [comment]
There are never enough eyes on copy :-)

**Comment by avive** [comment]
Should be fixed - lmk if you see any other typos - I'm pretty sure we got them!
